<a href="https://colab.research.google.com/github/boradenihal15-beep/Python-libraries/blob/main/Pandas/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DataFrame**

Dataset : https://drive.google.com/drive/folders/18ZsL5K8PiFT9GS1631lpGIE3HMR0n1G8

In [1]:
import pandas as pd
import numpy as np

In [73]:
#List
student_data=[
    [1,90,18],
    [2,50,17]
]
df_st=pd.DataFrame(student_data,columns=['Roll_no','Marks','Age'])
df_st.set_index('Roll_no',inplace=True)
print(df_st)

         Marks  Age
Roll_no
1           90   18
2           50   17

In [99]:
student_dict={
    'Name':['Nihal','karan','varan'],
    'Roll_no':[1,2,3],
    'Marks':[90,80,50],
    'Age':[18,17,18]
}
df_students=pd.DataFrame(student_dict)
df_students.set_index('Name',inplace=True)
print(df_students)

       Roll_no  Marks  Age
Name
Nihal        1     90   18
karan        2     80   17
varan        3     50   18

Reading the data

In [123]:
movies=pd.read_csv('movies.csv')
ipl=pd.read_csv('ipl-matches.csv')

Attributs and methods

In [27]:
#Shape
movies.shape

#dtype
movies.dtypes

#index
movies.index

#columns
movies.columns

#values
df_students.values

array([['Nihal', 90, 18],
       ['karan', 80, 17],
       ['varan', 50, 18]], dtype=object)

In [31]:
#head and tail
movies.head(6) #default 5

movies.tail(4) #default 5

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [34]:
#sample
movies.sample(3) #random row default 1

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1368,Meri Biwi Ka Jawaab Nahin,tt0187279,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Meri_Biwi_Ka_Jaw...,Meri Biwi Ka Jawab Nahin,Meri Biwi Ka Jawab Nahin,0,2004,150,Action|Comedy|Romance,3.9,627,Ajay gets married to his childhood friend Durg...,Ajay gets married to his childhood friend Durg...,NaN,Akshay Kumar|Sridevi|Gulshan Grover|Laxmikant ...,NaN,2 July 2004 (India)
649,Jackpot (2013 film),tt3309662,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jackpot_(2013_film),Jackpot,Jackpot,0,2013,132,Comedy|Thriller,2.0,657,Jackpot is a fast-paced thriller con with sha...,Jackpot is a fast-paced thriller con with sha...,NaN,Naseeruddin Shah|Sunny Leone|Sachiin Joshi|Bha...,NaN,13 December 2013 (India)
379,Roy (film),tt2976182,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Roy_(film),Roy,Roy,0,2015,146,Action|Drama|Mystery,3.3,6789,Kabir Grewal a Casanovic film maker and scree...,Successful film-maker Kabir meets with Ayesha ...,NaN,Arjun Rampal|Jacqueline Fernandez|Ranbir Kapoo...,5 wins & 6 nominations,12 February 2015 (Kuwait)

In [37]:
#info
movies.info()

#descibe
movies.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [46]:
#isnull
movies.isnull().sum()

#fillna
movies['wins_nominations'].fillna('0 wins') #filled Nan values with 0 wins

#dropna
movies.dropna() #mostly not used bcoz of loss of data

0                       4 wins
1                       0 wins
2                       0 wins
3                       0 wins
4       17 wins & 1 nomination
                 ...
1624                    0 wins
1625                    0 wins
1626                    0 wins
1627                    0 wins
1628                    0 wins
Name: wins_nominations, Length: 1629, dtype: object

In [49]:
#duplicates
movies.duplicated().sum()

np.int64(0)

In [68]:
#rename

#columns
df_students.rename(columns={'Name':'Naav','Marks':'Score'},inplace=True)
df_students

array(['Nihal', 90, 18], dtype=object)

# Maths Methods

In [77]:
#sum
df_students.sum(axis=0) #column wise
df_st.sum(axis=1) #row wise

#mean
df_st.mean(axis=1) #row wise

#variance
df_st.var(axis=1) #row wise

Roll_no
1    2592.0
2     544.5
dtype: float64

Selecting columns from Dataframe

In [79]:
#single colmns
movies['actors']

#multiple columns
movies[['actors','title_x']]

,actors,title_x
0,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,Uri: The Surgical Strike
1,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,Battalion 609
2,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,The Accidental Prime Minister (film)
3,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,Why Cheat India
4,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,Evening Shadows
...,...,...
1624,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,Tera Mera Saath Rahen
1625,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,Yeh Zindagi Ka Safar
1626,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,Sabse Bada Sukh
1627,Gippy Grewal|Zareen Khan|,Daaka
1628,Fawad Khan|,Humsafar

Selecting rows

In [109]:
#iloc
#use only in index is numrical

df_students.iloc[1]
df_students.iloc[[1,2]]
df_students[:2]
df_students[0::2]
df_students[::-1]

#loc
df_students.loc['Nihal']
df_students.loc[['Nihal','karan']]
df_students.loc['Nihal':'varan']
df_students.loc['Nihal':'varan':2]
df_students.loc[::-1]

       Roll_no  Marks  Age
Name
varan        3     50   18
karan        2     80   17
Nihal        1     90   18

Filtering

In [164]:
# find all the final winners
finals=ipl[ipl['MatchNumber']=='Final']
finals[['Season','WinningTeam']]

# how many super over finishes have occured
ipl[ipl['SuperOver']=='Y'].shape[0]

# how many matches has csk won in kolkata
ipl[(ipl['City']=='Kolkata') & (ipl['WinningTeam']=="Chennai Super Kings")].shape[0] #use & bitwise op

# toss winner is match winner in percentage
((ipl[ipl['TossWinner']==ipl['WinningTeam']].shape[0])/ipl.shape[0])*100

# movies with rating higher than 8 and votes>10000
movies[(movies['imdb_rating']>8.5) & (movies['imdb_votes']>10000)].shape[0]

# Action movies with rating higher than 7.5
movies[(movies['genres']=='Action') & (movies['imdb_rating']>7.5)]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
78,Dabangg 3,tt7059844,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dabangg_3,Dabangg 3,Dabangg 3,0,2019,160,Action,3.0,15000,Third installment of the Dabanng film series.,Third installment of the Dabanng film series.,NaN,Salman Khan|Sonakshi Sinha|Sudeep|Mahesh Manjr...,NaN,NaN
176,Aa Gaya Hero,tt5896934,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aa_Gaya_Hero,Aa Gaya Hero,Aa Gaya Hero,0,2017,123,Action,2.9,304,ACP Ravindra Varma a fearless and sincere pol...,ACP Ravindra Varma a fearless and sincere pol...,File of Abhinay Chakra.,Govinda|Richa Sharma|Poonam Pandey|Sweta Sharm...,NaN,16 March 2017 (India)
367,Gabbar Is Back,tt2424988,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gabbar_Is_Back,Gabbar is Back,Gabbar is Back,0,2015,128,Action,7.1,21430,Gabbar Singh Rajput (Akshay Kumar) creates his...,A grief-stricken man takes the law into his ow...,NaN,Akshay Kumar|Shruti Haasan|Kareena Kapoor|Jaid...,1 win,1 May 2015 (India)
368,Gabbar Is Back,tt2424988,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gabbar_is_Back,Gabbar is Back,Gabbar is Back,0,2015,128,Action,7.1,21430,Gabbar Singh Rajput (Akshay Kumar) creates his...,A grief-stricken man takes the law into his ow...,NaN,Akshay Kumar|Shruti Haasan|Kareena Kapoor|Jaid...,1 win,1 May 2015 (India)
435,Sorry Daddy,tt4994210,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sorry_Daddy_(film),Sorry Daddy,Sorry Daddy,0,2015,\N,Action,5.4,5,Inspector Ravi Sharma (Shamim Khan) is very ho...,Sorry daddy is a Children story centring aroun...,NaN,Shamim Khan|Mukesh Tiwari|,NaN,NaN
452,Ranbanka,tt5151622,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ranbanka,Ranbanka,Ranbanka,0,2015,98,Action,3.7,118,Rahul an engineer tries his best to protect ...,A non-violent engineer resorts to violence aft...,A Film By Aryeman,Manish Paul|Ravi Kishan|Pooja Thakur|Rudra Kau...,1 win,6 November 2015 (India)
535,Desi Kattey,tt3877652,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Desi_Kattey,Desi Kattey,Desi Kattey,0,2014,139,Action,4.2,111,A sharpshooting thug becomes a competitive sho...,A sharpshooting thug becomes a competitive sho...,NaN,Sasha Aagha|Tia Bajpai|Rajesh Bakshi|Jay Bhanu...,1 nomination,12 September 2014 (India)
538,Spark (2014 film),tt3893476,NaN,https://en.wikipedia.org/wiki/Spark_(2014_film),Spark,Spark,0,2014,134,Action,5.7,28,The story is about a local Indian lad Arjun (R...,The story is about a local Indian lad Arjun (R...,NaN,Rati Agnihotri|Mansha Bahl|Rajniesh Duggall|Su...,NaN,10 October 2014 (India)
637,Boss (2013 Hindi film),tt2571140,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Boss_(2013_Hindi...,Boss,Boss,0,2013,143,Action,5.1,9674,Boss (Akshay Kumar) takes the blame for a murd...,A man fights for people's rights. In Delhi he...,The BOSS is here.,Akshay Kumar|Shiv Panditt|Mithun Chakraborty|R...,NaN,16 October 2013 (India)
1146,Adharm (2006 film),tt2435680,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Adharm_(2006_film),Adharm,Adharm,0,2006,\N,Action,5.1,7,This story is inspired by true incident that h...,This story is inspired by true incident that h...,NaN,Rahul Dev|Mayuri Kango|Rocky Khanna|Anupam Khe...,NaN,NaN
1171,Dharti Kahe Pukar Ke (2006 film),tt5216486,https://upload.wikimedia.org/wikipedia/en/6/64...,https://en.wikipedia.org/wiki/Dharti_Kahe_Puka...,Dharti Kahe Pukar Ke,Dharti Kahe Pukar Ke,0,2006,\N,Action,6.3,7,NaN,Add a Plot »,NaN,Ajay Devgn|Sharbani Mukherjee|,NaN,NaN
1310,Vidyaarthi,tt1483815,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Vidyaarthi,Vidhyaarthi: The Power of Students,Vidhyaarthi: The Power of Students,0,2006,250,Action,5.0,8,This story about underworld and crime. How can...,This story about underworld and crime. How can...,The power of students,Vikram Aditya|Akash Ajmera|Ishrat Ali|Rajesh B...,NaN,18 June 2006 (India)
1411,Aaj Ka Andha Kanoon,tt0426863,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aaj_Ka_Andha_Kanoon,Aaj Ka Andha Kanoon,Aaj Ka Andha Kanoon,0,2003,46,Action,3.3,14,Deva comes to the city in search of work! He m...,Deva comes to the city in search of work! He m...,NaN,Sudesh Berry|Priyanka Upendra|Aman Jalali|Vish...,NaN,10 June 2003 (India)
1585,Bhairav (film),tt0466208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bhairav_(film),Bhairav,Bhairav,0,2001,133,Action,5.0,23,Rakesh Pandey belongs to a middle-class family...,Rakesh Pandey belongs to a middle-class family...,NaN,Hemant Birje|Mithun Chakraborty|Jack Gaud|Brij...,NaN,2001 (India)
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)