<a href="https://colab.research.google.com/github/boradenihal15-beep/Python-libraries/blob/main/Pandas/Grouping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

# Grouping

* Grouping is used to group the data in categories.

* it makes easy to perform  aggregate methods on categories.

* e.g calculating highest marks of student from each dept.

In [4]:
movies=pd.read_csv('imdb-top-1000.csv')
dev=pd.read_csv('deliveries.csv')

In [5]:
#groupby

movies.groupby('Genre').max()['IMDB_Rating']#applied agg method max to get max rating for each genre

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [6]:
# find the top 3 genres by total earning

movies.groupby('Genre').sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [7]:
# find the genre with highest avg IMDB rating
movies.groupby("Genre")['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [8]:
# find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [9]:
# find the highest rated movie of each genre
movies.groupby(['Genre'])['IMDB_Rating'].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [10]:
# find number of movies done by each actor
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks            12
Robert De Niro       11
Clint Eastwood       10
Al Pacino            10
Leonardo DiCaprio     9
                     ..
Gérard Jugnot         1
Günes Sensoy          1
Haluk Bilginer        1
Harriet Andersson     1
Graham Chapman        1
Name: Series_Title, Length: 660, dtype: int64

In [11]:
#groupby attributes and methods

#len
print(len(movies.groupby("Genre"))) #Total number of groups

#size
movies.groupby("Genre").size() #Total items in each group

#first()/last()/nth() value
genre=movies.groupby('Genre')
genre.first() #first value of each genre
genre.last() #last value of each genre
genre.nth(6) #6th movie of each  genre

14

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [12]:
#fetch a group

genre.get_group('Action')
#or
movies[movies['Genre']=='Action']

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
968,Falling Down,1993,113,Action,7.6,Joel Schumacher,Michael Douglas,171640,40903593.0,56.0
979,Lethal Weapon,1987,109,Action,7.6,Richard Donner,Mel Gibson,236894,65207127.0,68.0
982,Mad Max 2,1981,96,Action,7.6,George Miller,Mel Gibson,166588,12465371.0,77.0
983,The Warriors,1979,92,Action,7.6,Walter Hill,Michael Beck,93878,22490039.0,65.0
985,Escape from Alcatraz,1979,112,Action,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0

In [13]:
#get groups and values

genre.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [14]:
#descibe

#stats of each genre
genre.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [15]:
#sample

#random value from each genre
genre.sample(2,replace=True) #if want custom no of values

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
930,Watchmen,2009,162,Action,7.6,Zack Snyder,Jackie Earle Haley,500799,107509799.0,56.0
887,Guardians of the Galaxy Vol. 2,2017,136,Action,7.6,James Gunn,Chris Pratt,569974,389813101.0,67.0
957,Fear and Loathing in Las Vegas,1998,118,Adventure,7.6,Terry Gilliam,Johnny Depp,259753,10680275.0,41.0
426,Planet of the Apes,1968,112,Adventure,8.0,Franklin J. Schaffner,Charlton Heston,165167,33395426.0,79.0
330,Zootopia,2016,108,Animation,8.0,Byron Howard,Rich Moore,434143,341268248.0,78.0
219,Song of the Sea,2014,93,Animation,8.1,Tomm Moore,David Rawle,51679,857524.0,85.0
176,The Message,1976,177,Biography,8.2,Moustapha Akkad,Anthony Quinn,43885,216427395.0,NaN
809,Donnie Brasco,1997,127,Biography,7.7,Mike Newell,Al Pacino,279318,41909762.0,76.0
680,Down by Law,1986,107,Comedy,7.8,Jim Jarmusch,Tom Waits,47834,1436000.0,75.0
538,Amarcord,1973,123,Comedy,7.9,Federico Fellini,Magali Noël,39897,882861253.0,NaN
833,Der Name der Rose,1986,130,Crime,7.7,Jean-Jacques Annaud,Sean Connery,102031,7153487.0,54.0
885,Victoria,2015,138,Crime,7.6,Sebastian Schipper,Laia Costa,52903,718096942.0,77.0
925,The Illusionist,2006,110,Drama,7.6,Neil Burger,Edward Norton,354728,39868642.0,68.0
278,The Deer Hunter,1978,183,Drama,8.1,Michael Cimino,Robert De Niro,311361,48979328.0,86.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
961,Lost Highway,1997,134,Mystery,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [16]:
#nunique

genre.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [17]:
#agg
genre.sum()
# genre.mean()

#This method of applying aggregate method will give agg for all columns with different output
#but what if we want to apply diff agg to diff column
#then we use agg using dict

genre.agg({
    'Runtime':'mean',
    'IMDB_Rating':'sum',
    'Metascore':'max'
})
#so we can apply any agg to any column

#agg using list
#if we want to apply multiple agg to each column we pass list of agg methods

genre.agg(['sum','max','min']) #now we can get all three agg to each colmn

genre[['Runtime','IMDB_Rating','Metascore']].agg(['mean','sum','min','max'])

#also we can combine both methods
genre.agg({
    'Runtime':['mean','sum'],
    'IMDB_Rating':['max','min'],
    'Metascore':['max','mean']
})

              Runtime        IMDB_Rating      Metascore
                 mean    sum         max  min       max       mean
Genre
Action     129.046512  22196         9.0  7.6      98.0  73.419580
Adventure  134.111111   9656         8.6  7.6     100.0  78.437500
Animation   99.585366   8166         8.6  7.6      96.0  81.093333
Biography  136.022727  11970         8.9  7.6      97.0  76.240506
Comedy     112.129032  17380         8.6  7.6      99.0  78.720000
Crime      126.392523  13524         9.2  7.6     100.0  77.080460
Drama      124.737024  36049         9.3  7.6     100.0  79.701245
Family     107.500000    215         7.8  7.8      91.0  79.000000
Fantasy     85.000000    170         8.1  7.9       NaN        NaN
Film-Noir  104.000000    312         8.1  7.8      97.0  95.666667
Horror     102.090909   1123         8.5  7.6      97.0  80.000000
Mystery    119.083333   1429         8.4  7.6     100.0  79.125000
Thriller   108.000000    108         7.8  7.8      81.0  81.000000
Western    148.250000    593         8.8  7.8      90.0  78.250000

In [18]:
#Looping
df=[]
for group,data in genre:
  max_rating=data[data['IMDB_Rating']==data['IMDB_Rating'].max()]
  df.append(max_rating[['Genre','Series_Title']])

df=pd.concat(df)
df

         Genre                         Series_Title
2       Action                      The Dark Knight
21   Adventure                         Interstellar
23   Animation        Sen to Chihiro no kamikakushi
7    Biography                     Schindler's List
19      Comedy                         Gisaengchung
26      Comedy                      La vita è bella
1        Crime                        The Godfather
0        Drama             The Shawshank Redemption
688     Family           E.T. the Extra-Terrestrial
698     Family  Willy Wonka & the Chocolate Factory
321    Fantasy         Das Cabinet des Dr. Caligari
309  Film-Noir                        The Third Man
49      Horror                               Psycho
69     Mystery                              Memento
81     Mystery                          Rear Window
700   Thriller                      Wait Until Dark
12     Western      Il buono, il brutto, il cattivo

In [19]:
#apply
#split apply combine
#we can apply buildin or custom methods on groups
#basically we split data,apply some function and combine it with grouped data

# find number of movies starting with A for each group
def foo(group):
  return group['Series_Title'].str.startswith("A").sum()

genre.apply(foo)

/tmp/ipykernel_4081/3785598078.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [24]:
# find ranking of each movie in the group according to IMDB score
def ranking(group):
  group['Genre_Raking']=group['IMDB_Rating'].rank(ascending=False)
  return group

genre.apply(ranking)

/tmp/ipykernel_4081/1601135037.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(ranking)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              Genre_rank  Genre_Raking
Genre
Action   2           4.0           1.0
         5           7.0           2.0
         8          11.0           3.5
         10         11.0           3.5
         13         16.0           6.0
...                  ...           ...
Thriller 700       645.0           1.0
Western  12         11.0           1.0
         48         43.5           2.0
         115       106.5           3.0
         691       645.0           4.0

[1000 rows x 12 columns]

In [27]:
# find normalized IMDB rating group wise
#normalize (x-xmin/xmax-xmin)

def normal(group):
  group['Normalize']=(group['IMDB_Rating']-group['IMDB_Rating'].min())/(group['IMDB_Rating'].max()-group['IMDB_Rating'].min())
  return group
genre.apply(normal)

/tmp/ipykernel_4081/1579331845.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              Genre_rank  Normalize
Genre
Action   2           4.0   1.000000
         5           7.0   0.928571
         8          11.0   0.857143
         10         11.0   0.857143
         13         16.0   0.785714
...                  ...        ...
Thriller 700       645.0        NaN
Western  12         11.0   1.000000
         48         43.5   0.700000
         115       106.5   0.500000
         691       645.0   0.000000

[1000 rows x 12 columns]

In [38]:
# groupby on multiple cols
Series=movies.groupby(['Genre','Series_Title'])

Streaming output truncated to the last 5000 lines.
         Director          Star1  No_of_Votes       Gross  Metascore  \
179  John Sturges  Steve McQueen       224730  12100000.0       86.0

     Genre_rank
179       162.0
                          Series_Title Released_Year  Runtime      Genre  \
618  The Hobbit: An Unexpected Journey          2012      169  Adventure

     IMDB_Rating       Director           Star1  No_of_Votes        Gross  \
618          7.8  Peter Jackson  Martin Freeman       757377  303003568.0

     Metascore  Genre_rank
618       58.0       645.0
                            Series_Title Released_Year  Runtime      Genre  \
609  The Hobbit: The Desolation of Smaug          2013      161  Adventure

     IMDB_Rating       Director         Star1  No_of_Votes        Gross  \
609          7.8  Peter Jackson  Ian McKellen       601408  258366855.0

     Metascore  Genre_rank
609       66.0       645.0
                  Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
692  The Man Who Would Be King          1975      129  Adventure          7.8

        Director         Star1  No_of_Votes        Gross  Metascore  \
692  John Huston  Sean Connery        44917  335861628.0       91.0

     Genre_rank
692       645.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating      Director  \
329  The Martian          2015      144  Adventure          8.0  Ridley Scott

          Star1  No_of_Votes        Gross  Metascore  Genre_rank
329  Matt Damon       760094  228433663.0       80.0       393.0
         Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
984  The Muppet Movie          1979       95  Adventure          7.6

          Director       Star1  No_of_Votes       Gross  Metascore  Genre_rank
984  James Frawley  Jim Henson        32802  76657000.0       74.0       939.0
                 Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
884  The Peanut Butter Falcon          2019       97  Adventure          7.6

         Director             Star1  No_of_Votes       Gross  Metascore  \
884  Tyler Nilson  Michael Schwartz        66346  13122642.0       70.0

     Genre_rank
884       939.0
           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
406  The Princess Bride          1987       98  Adventure          8.0

       Director       Star1  No_of_Votes       Gross  Metascore  Genre_rank
406  Rob Reiner  Cary Elwes       393899  30857814.0       77.0       393.0
        Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
686  The Right Stuff          1983      193  Adventure          7.8

           Director        Star1  No_of_Votes       Gross  Metascore  \
686  Philip Kaufman  Sam Shepard        56235  21500000.0       91.0

     Genre_rank
686       645.0
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating   Director  \
553  The Searchers          1956      119  Adventure          7.9  John Ford

          Star1  No_of_Votes        Gross  Metascore  Genre_rank
553  John Wayne        80316  538886182.0       94.0       516.5
             Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
552  The Ten Commandments          1956      220  Adventure          7.9

             Director            Star1  No_of_Votes       Gross  Metascore  \
552  Cecil B. DeMille  Charlton Heston        63560  93740000.0        NaN

     Genre_rank
552       516.5
                         Series_Title Released_Year  Runtime      Genre  \
191  The Treasure of the Sierra Madre          1948      126  Adventure

     IMDB_Rating     Director            Star1  No_of_Votes      Gross  \
191          8.2  John Huston  Humphrey Bogart       114304  5014000.0

     Metascore  Genre_rank
191       98.0       162.0
         Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
458  The Wizard of Oz          1939      102  Adventure          8.0

           Director         Star1  No_of_Votes      Gross  Metascore  \
458  Victor Fleming  George Cukor       371379  2076020.0       92.0

     Genre_rank
458       393.0
             Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
711  To Have and Have Not          1944      100  Adventure          7.8

         Director            Star1  No_of_Votes        Gross  Metascore  \
711  Howard Hawks  Humphrey Bogart        31053  477606207.0        NaN

     Genre_rank
711       645.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating      Director  \
323         Togo          2019      113  Adventure          8.0  Ericson Core

            Star1  No_of_Votes        Gross  Metascore  Genre_rank
323  Willem Dafoe        37556  874211619.0       69.0       393.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
912   Zombieland          2009       88  Adventure          7.6

            Director            Star1  No_of_Votes       Gross  Metascore  \
912  Ruben Fleischer  Jesse Eisenberg       520041  75590286.0       73.0

     Genre_rank
912       939.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
405        Akira          1988      124  Animation          8.0

            Director         Star1  No_of_Votes     Gross  Metascore  \
405  Katsuhiro Ôtomo  Mitsuo Iwata       164918  553171.0        NaN

     Genre_rank
405       393.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating      Director  \
399      Aladdin          1992       90  Animation          8.0  Ron Clements

           Star1  No_of_Votes        Gross  Metascore  Genre_rank
399  John Musker       373845  217350219.0       86.0       393.0
                     Series_Title Released_Year  Runtime      Genre  \
665  Batman: Mask of the Phantasm          1993       76  Animation

     IMDB_Rating       Director          Star1  No_of_Votes      Gross  \
665          7.8  Kevin Altieri  Boyd Kirkland        43690  5617391.0

     Metascore  Genre_rank
665        NaN       645.0
             Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
401  Beauty and the Beast          1991       84  Animation          8.0

           Director      Star1  No_of_Votes        Gross  Metascore  \
401  Gary Trousdale  Kirk Wise       417178  218967620.0       95.0

     Genre_rank
401       393.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  Director  \
592   Big Hero 6          2014      102  Animation          7.8  Don Hall

              Star1  No_of_Votes        Gross  Metascore  Genre_rank
592  Chris Williams       410983  222527828.0       74.0       645.0
   Series_Title Released_Year  Runtime      Genre  IMDB_Rating     Director  \
61         Coco          2017      105  Animation          8.4  Lee Unkrich

            Star1  No_of_Votes        Gross  Metascore  Genre_rank
61  Adrian Molina       384171  209726015.0       81.0        69.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating      Director  \
783     Coraline          2009      100  Animation          7.7  Henry Selick

              Star1  No_of_Votes       Gross  Metascore  Genre_rank
783  Dakota Fanning       197761  75286229.0       80.0       799.0
                        Series_Title Released_Year  Runtime      Genre  \
510  Cowboy Bebop: Tengoku no tobira          2001      115  Animation

     IMDB_Rating              Director           Star1  No_of_Votes  \
510          7.9  Shin'ichirô Watanabe  Tensai Okamura        42897

         Gross  Metascore  Genre_rank
510  1000045.0       61.0       516.5
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
906  Despicable Me          2010       95  Animation          7.6

          Director         Star1  No_of_Votes        Gross  Metascore  \
906  Pierre Coffin  Chris Renaud       500851  251513985.0       72.0

     Genre_rank
906       939.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating     Director  \
875     Fantasia          1940      125  Animation          7.7  James Algar

                Star1  No_of_Votes       Gross  Metascore  Genre_rank
875  Samuel Armstrong        88662  76408097.0       96.0       799.0
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
499  Fantastic Mr. Fox          2009       87  Animation          7.9

         Director           Star1  No_of_Votes       Gross  Metascore  \
499  Wes Anderson  George Clooney       199696  21002919.0       83.0

     Genre_rank
499       516.5
     Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
242  Finding Nemo          2003      100  Animation          8.1

           Director        Star1  No_of_Votes        Gross  Metascore  \
242  Andrew Stanton  Lee Unkrich       949565  380843261.0       90.0

     Genre_rank
242       259.0
            Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
756  Gake no ue no Ponyo          2008      101  Animation          7.7

           Director           Star1  No_of_Votes       Gross  Metascore  \
756  Hayao Miyazaki  Cate Blanchett       125317  15090400.0       86.0

     Genre_rank
756       799.0
             Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
158  Hauru no ugoku shiro          2004      119  Animation          8.2

           Director          Star1  No_of_Votes      Gross  Metascore  \
158  Hayao Miyazaki  Chieko Baishô       333915  4711096.0       80.0

     Genre_rank
158       162.0
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
46  Hotaru no haka          1988       89  Animation          8.5

         Director            Star1  No_of_Votes        Gross  Metascore  \
46  Isao Takahata  Tsutomu Tatsumi       235231  150734678.0       94.0

    Genre_rank
46        43.5
                 Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
230  How to Train Your Dragon          2010       98  Animation          8.1

         Director          Star1  No_of_Votes        Gross  Metascore  \
230  Dean DeBlois  Chris Sanders       666773  217581231.0       75.0

     Genre_rank
230       259.0
                   Series_Title Released_Year  Runtime      Genre  \
599  How to Train Your Dragon 2          2014      102  Animation

     IMDB_Rating      Director         Star1  No_of_Votes        Gross  \
599          7.8  Dean DeBlois  Jay Baruchel       305611  177002924.0

     Metascore  Genre_rank
599       76.0       645.0
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating   Director  \
891  Incredibles 2          2018      118  Animation          7.6  Brad Bird

               Star1  No_of_Votes        Gross  Metascore  Genre_rank
891  Craig T. Nelson       250057  608581744.0       80.0       939.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating     Director  \
213   Inside Out          2015       95  Animation          8.1  Pete Docter

                 Star1  No_of_Votes        Gross  Metascore  Genre_rank
213  Ronnie Del Carmen       616228  356461711.0       94.0       259.0
     Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
469  Isle of Dogs          2018      101  Animation          7.9

         Director           Star1  No_of_Votes       Gross  Metascore  \
469  Wes Anderson  Bryan Cranston       139114  32015231.0       82.0

     Genre_rank
469       516.5
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
522  Jûbê ninpûchô          1993       94  Animation          7.9

              Director            Star1  No_of_Votes        Gross  Metascore  \
522  Yoshiaki Kawajiri  Kôichi Yamadera        34529  713576404.0        NaN

     Genre_rank
522       516.5
                 Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
332  Kaguyahime no monogatari          2013      137  Animation          8.0

          Director               Star1  No_of_Votes      Gross  Metascore  \
332  Isao Takahata  Chloë Grace Moretz        38746  1506975.0       89.0

     Genre_rank
332       393.0
                Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
902  Kari-gurashi no Arietti          2010       94  Animation          7.6

                 Director        Star1  No_of_Votes       Gross  Metascore  \
902  Hiromasa Yonebayashi  Amy Poehler        80939  19202743.0       80.0

     Genre_rank
902       939.0
                 Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
270  Kaze no tani no Naushika          1984      117  Animation          8.1

           Director           Star1  No_of_Votes     Gross  Metascore  \
270  Hayao Miyazaki  Sumi Shimamoto       150924  495770.0       86.0

     Genre_rank
270       259.0
     Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
595  Kaze tachinu          2013      126  Animation          7.8

           Director         Star1  No_of_Votes      Gross  Metascore  \
595  Hayao Miyazaki  Hideaki Anno        73690  5209580.0       83.0

     Genre_rank
595       645.0
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
56  Kimi no na wa.          2016      106  Animation          8.4

          Director             Star1  No_of_Votes      Gross  Metascore  \
56  Makoto Shinkai  Ryûnosuke Kamiki       194838  5017246.0       79.0

    Genre_rank
56        69.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
135        Klaus          2019       96  Animation          8.2

          Director                  Star1  No_of_Votes        Gross  \
135  Sergio Pablos  Carlos Martínez López       104761  148596026.0

     Metascore  Genre_rank
135       65.0       162.0
       Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
197  Koe no katachi          2016      130  Animation          8.1

         Director       Star1  No_of_Votes       Gross  Metascore  Genre_rank
197  Naoko Yamada  Miyu Irino        47708  37039721.0       78.0       259.0
                 Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
578  Kubo and the Two Strings          2016      101  Animation          7.8

          Director            Star1  No_of_Votes       Gross  Metascore  \
578  Travis Knight  Charlize Theron       118035  48023088.0       84.0

     Genre_rank
578       645.0
        Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
822  Kurenai no buta          1992       94  Animation          7.7

           Director               Star1  No_of_Votes        Gross  Metascore  \
822  Hayao Miyazaki  Shûichirô Moriyama        77798  871544815.0       83.0

     Genre_rank
822       799.0
       Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
394  Kôkaku Kidôtai          1995       83  Animation          8.0

         Director          Star1  No_of_Votes     Gross  Metascore  Genre_rank
394  Mamoru Oshii  Atsuko Tanaka       129231  515905.0       76.0       393.0
           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
694  La planète sauvage          1973       72  Animation          7.8

        Director           Star1  No_of_Votes     Gross  Metascore  Genre_rank
694  René Laloux  Barry Bostwick        25229  193817.0       73.0       645.0
        Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
741  Le Petit Prince          2015      108  Animation          7.7

         Director         Star1  No_of_Votes      Gross  Metascore  Genre_rank
741  Mark Osborne  Jeff Bridges        56720  1339152.0       70.0       799.0
                     Series_Title Released_Year  Runtime      Genre  \
640  Les triplettes de Belleville          2003       80  Animation

     IMDB_Rating        Director               Star1  No_of_Votes      Gross  \
640          7.8  Sylvain Chomet  Michèle Caucheteux        50622  7002255.0

     Metascore  Genre_rank
640       91.0       645.0
       Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
586  Loving Vincent          2017       94  Animation          7.8

           Director          Star1  No_of_Votes      Gross  Metascore  \
586  Dorota Kobiela  Hugh Welchman        50778  6735118.0       62.0

     Genre_rank
586       645.0
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
672  Majo no takkyûbin          1989      103  Animation          7.8

           Director          Star1  No_of_Votes       Gross  Metascore  \
672  Hayao Miyazaki  Kirsten Dunst       124193  58564351.0       83.0

     Genre_rank
672       645.0
     Series_Title Released_Year  Runtime      Genre  IMDB_Rating     Director  \
229  Mary and Max          2009       92  Animation          8.1  Adam Elliot

             Star1  No_of_Votes        Gross  Metascore  Genre_rank
229  Toni Collette       164462  873839108.0        NaN       259.0
         Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
518  Mimi wo sumaseba          1995      111  Animation          7.9

            Director       Star1  No_of_Votes        Gross  Metascore  \
518  Yoshifumi Kondô  Yoko Honna        51943  252243550.0       75.0

     Genre_rank
518       516.5
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating      Director  \
892        Moana          2016      107  Animation          7.6  Ron Clements

           Star1  No_of_Votes        Gross  Metascore  Genre_rank
892  John Musker       272784  248757044.0       81.0       939.0
     Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
70  Mononoke-hime          1997      134  Animation          8.4

          Director         Star1  No_of_Votes      Gross  Metascore  \
70  Hayao Miyazaki  Yôji Matsuda       343171  2375308.0       76.0

    Genre_rank
70        69.0
       Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
245  Monsters, Inc.          2001       92  Animation          8.1

        Director            Star1  No_of_Votes        Gross  Metascore  \
245  Pete Docter  David Silverman       815505  289916256.0       79.0

     Genre_rank
245       259.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
956        Mulan          1998       88  Animation          7.6

          Director       Star1  No_of_Votes        Gross  Metascore  \
956  Tony Bancroft  Barry Cook       256906  120620254.0       71.0

     Genre_rank
956       939.0
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
971  Omohide poro poro          1991      118  Animation          7.6

          Director      Star1  No_of_Votes     Gross  Metascore  Genre_rank
971  Isao Takahata  Miki Imai        27071  453243.0       90.0       939.0
       Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
728  Omoide no Mânî          2014      103  Animation          7.7

         Director                 Star1  No_of_Votes     Gross  Metascore  \
728  James Simone  Hiromasa Yonebayashi        32798  765127.0       72.0

     Genre_rank
728       799.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating     Director  \
758     Papurika          2006       90  Animation          7.7  Satoshi Kon

                  Star1  No_of_Votes     Gross  Metascore  Genre_rank
758  Megumi Hayashibara        71379  881302.0       81.0       799.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
358   Persepolis          2007       96  Animation          8.0

              Director            Star1  No_of_Votes      Gross  Metascore  \
358  Vincent Paronnaud  Marjane Satrapi        88656  4445756.0       90.0

     Genre_rank
358       393.0
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
386  Pâfekuto burû          1997       81  Animation          8.0

        Director       Star1  No_of_Votes     Gross  Metascore  Genre_rank
386  Satoshi Kon  Junko Iwao        58192  776665.0        NaN       393.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating   Director  \
367  Ratatouille          2007      111  Animation          8.0  Brad Bird


In [42]:
# find the most earning actor->director combo
movies.groupby(['Director','Star1'])['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [55]:
# find the best(in-terms of metascore(avg)) actor->genre combo
movies.groupby(['Star1','Genre'])['Metascore'].mean().sort_values(ascending=False).head(1)

Star1          Genre
Peter O'Toole  Adventure    100.0
Name: Metascore, dtype: float64

In [63]:
# agg on multiple groupby
duo=movies.groupby(['Director','Star1'])

duo.agg({
    'IMDB_Rating':['min','max'],
    'Gross':['sum','mean']
})

                                   IMDB_Rating             Gross
                                           min  max          sum         mean
Director            Star1
Aamir Khan          Amole Gupte            8.4  8.4    1223869.0    1223869.0
Aaron Sorkin        Eddie Redmayne         7.8  7.8  853090410.0  853090410.0
Abdellatif Kechiche Léa Seydoux            7.7  7.7    2199675.0    2199675.0
Abhishek Chaubey    Shahid Kapoor          7.8  7.8  218428303.0  218428303.0
Abhishek Kapoor     Amit Sadh              7.7  7.7    1122527.0    1122527.0
...                                        ...  ...          ...          ...
Zaza Urushadze      Lembit Ulfsak          8.2  8.2     144501.0     144501.0
Zoya Akhtar         Hrithik Roshan         8.1  8.1    3108485.0    3108485.0
                    Vijay Varma            8.0  8.0    5566534.0    5566534.0
Çagan Irmak         Çetin Tekindor         8.3  8.3  461855363.0  461855363.0
Ömer Faruk Sorak    Cem Yilmaz             8.0  8.0  196206077.0  196206077.0

[898 rows x 4 columns]

# Exercise